config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products do
    resources :reviews
  end
  root to: 'products#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :cost, presence: true
  validates :country_of_origin, presence: true
  has_one_attached :product_photo

  before_save(:titleize_product)

  scope :three_most_recent, -> {order(created_at: :desc).limit(3)}

  scope :three_most_reviews, -> {select("products.*, count(reviews.id) as most_review").joins(:reviews).group("products.id").order("most_review DESC").limit(3)}

  scope :made_in_usa, -> {where(country_of_origin: "United States Of America")}

  private
  def titleize_product
    self.name = self.name.titleize
    self.country_of_origin = self.country_of_origin.titleize
  end
end

app/models/review.rb
class Review < ApplicationRecord
  
  belongs_to :product

  validates :author, presence: true

  validates :rating, presence: true
  
  validates_numericality_of :rating, greater_than: 0, less_than: 6, message: "Please rate from 1 to 5"

  validates :content_body,  presence: true, length: {in: 50..250, message: "Contents must be between 50 and 250 characters"}
 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :is_admin?

  def is_admin?
    current_user && current_user.admin
  end

  def authorized_admin?
    redirect_to products_path unless is_admin?
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, :except => [:home]
  before_action :authorized_admin?, :only => [:new, :edit, :create, :destroy, :update]
  
  def index
    @products = Product.all.order("created_at DESC")
    @most_recent_products = Product.three_most_recent
    @most_reviews = Product.three_most_reviews
    @made_in_usa = Product.made_in_usa
    render :index
  end

  def home
    @most_recent_products = Product.three_most_recent
    @most_reviews = Product.three_most_reviews
    render :home
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    @product.product_photo.attach(params[:product][:product_photo])
    if @product.save
      flash[:notice] = "New product added!"
      redirect_to products_path
    else
      flash[:notice] = "Something went wrong"
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def update
    @product= Product.find(params[:id])
    @product.product_photo.attach(params[:product][:product_photo])
    if @product.update(product_params)
      flash[:notice] = "Product updated!"
      redirect_to products_path
    else
      render :edit
    end
  end

  def show
    @product = Product.find(params[:id])
    render :show
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product deleted!"
    redirect_to products_path
  end

  private
    def product_params
      params.require(:product).permit(:name, :cost, :country_of_origin)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorized_admin?, :only => [:edit, :destroy, :update]

  def new
      @product = Product.find(params[:product_id])
      @review = @product.reviews.new
      render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "New review added!"
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash[:notice] = "Review updated!"
      redirect_to product_path(@review.product)
    else
      flash[:notice] = "Review has not been updated!"
      @product = @review.product
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = "Review deleted"
    redirect_to product_path(@review.product)
  end

  private
    def review_params
      params.require(:review).permit(:author, :content_body, :rating)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFoodProducts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class="container">
        <nav class="navbar navbar-dark bg-dark">
          <a class="navbar-brand" href="/">Home</a>
          <a class="navbar-brand" href="/products">View Product</a>
          <% if current_user %>
            <a class="navbar-brand" href="#"> Signed in as <%= current_user.email %> </a>
            <a class="navbar-brand" href="/users/sign_out" data-method="delete" value="<%= destroy_user_session_path%>">Sign Out</a>
          <% else %>
            <a class="navbar-brand" href="/users/sign_in">Sign in</a>
            <a class="navbar-brand" href="/users/sign_up">Sign up</a>
          <% end %>  
        </nav>
            <%= flash[:notice] %>
            <%= yield %>
        </div>
      </div>
  </body>
</html>

app/views/products/edit.html.erb
<h2>Edit this product</h2>

<%= form_for @product do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :cost %>
    <%= f.text_field :cost %>
  </div>
  <div class="form-group">
    <%= f.label :country_of_origin %>
    <%= f.text_field :country_of_origin %>
  </div>
  <div class="form-group">
    <%= f.label :product_photo %>
    <%= f.file_field :product_photo %>
  </div>
  <div>
    <%= f.submit  %>
  </div>
<% end %>

app/views/products/home.html.erb
<div class="text-center">

  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h2 class="display-4">Welcome to Mario Food Products</h2>
      <p class="lead">The longest-operating vegetables retailer in the US.</p>
    </div>
  </div>

  <div>
    <%= link_to "See Products", products_path, class:"btn btn-success" %>
  </div>

  <div class="row">

    <div class="col-sm-6">
      <div class="most-recent">
        <h3>Most recent products</h3>
          <% @most_recent_products.each do |most_recent| %>
            <li> <%= most_recent.name %> NEW!!!</li>
          <% end%>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="most-reviewed">
        <h3>Most reviewed products</h3>
          <% @most_reviews.each do |most_review| %>
            <li> <%= most_review.name %> HOT!!!</li>
          <% end%>
      </div>
    </div>

  </div>

</div>

app/views/products/index.html.erb
<h1>Mario's Food Products</h1>
<h3>Current products</h3>

<h3>Made in USA</h3>
<% if @made_in_usa.any? %>
  <ul>
    <% @made_in_usa.each do |product| %>
      <li>
        <%= link_to product.name, product_path(product) %>
      </li>
      <% end %>
  </ul>
<% else %>
   <p>There are no made in USA products yet.</p>
<% end %>
  
<h3>Others</h3>
<% if @products.any? %>
  <ul>
    <% @products.each do |product| %>
      <li>
        <%= link_to product.name, product_path(product) %> made in <%= product.country_of_origin %> 
          <% if @most_recent_products.include?(product) %> 
           <span class="text-primary">  New!!! </span>
          <% end %>  
          <% if @most_reviews.include?(product) %> 
            <span class="text-danger">  Hot!!! </span>
          <% end %>  
      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no products yet.</p>
<% end %>

<p><%= link_to "Create new product", new_product_path %></p>

app/views/products/new.html.erb
<h2>Add a new product</h2>

<% if @product.errors.any? %>
  <h3>...Something went wrong. Please fix these errors:</h3>
  <ul>
    <% @product.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_for @product do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :cost %>
    <%= f.text_field :cost %>
  </div>
  <div class="form-group">
    <%= f.label :country_of_origin %>
    <%= f.text_field :country_of_origin %>
  </div>
  <div class="form-group">
    <%= f.label :product_photo %>
    <%= f.file_field :product_photo %>
  </div>
  <div>
    <%= f.submit  %>
  </div>
<% end %>

app/views/products/show.html.erb
<h2><%= "Product name: #{@product.name}" %></h2>
<h4><%= "Cost: $ #{@product.cost}" %></h4>
<h4><%= "Country of origin: #{@product.country_of_origin}" %></h4>

<% if @product.product_photo.attached? %>
  <%= image_tag @product.product_photo, :size =>'250x250' %>
<% end %>

<% if @product.reviews.any? %>
  <h4> The reviews for this product: </h4>
  <% @product.reviews.each do |review| %>
    <ul>
      <li>
        <p><%= link_to "#{review.rating} star rating by #{ review.author}", product_review_path(@product, review) %> </p>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No reviews are listed for this product.</p>
<% end %>

<div class="fixed-bottom">
  <p><%= link_to "Add a review to this product", new_product_review_path(@product) %></p>
  <p><%= link_to "Edit this product", edit_product_path(@product) %></p>
  <p><%= link_to "Delete", product_path(@product),
                          :data => {:confirm => "You sure?",
                                    :method => "delete"} %></p>

  <p><%= link_to "Return to products", products_path %></p>
</div>

app/views/reviews/edit.html.erb
<h2>Edit review of "<%= @product.name %>" </h2>

<%= form_for [@product, @review] do |f| %>
  <div class="form-group">
    <%= f.label :author, "Name" %>
    <%= f.text_field :author %>
  </div>
  <div class="form-group">
    <%= f.label :content_body %>
    <%= f.text_area :content_body %>
  </div>
  <div class="form-group">
    <%= f.label :rating %>
    <%= f.text_field :rating %>
  </div>
  <div>
    <%= f.submit  %>
  </div>
<% end %>

app/views/reviews/new.html.erb
<h2>Add a new review for "<%= @product.name %>" </h2>

<% if @review.errors.any? %>
  <h4>...Something went wrong. Please fix these errors:</h4>
  <ul>
    <% @review.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for [@product, @review] do |f| %>
  <div class="form-group">
    <%= f.label :author, "Name" %>
    <%= f.text_field :author %>
  </div>
  <div class="form-group">
    <%= f.label :content_body %>
    <%= f.text_area :content_body %>
  </div>
  <div class="form-group">
    <%= f.label :rating, "Rate this product" %>
    <%= f.text_field :rating %>
  </div>
  <div>
    <%= f.submit  %>
  </div>
<% end %>

app/views/reviews/show.html.erb
<h2>Review by: <%= @review.author %></h2>
<h3>Product name: <%= @product.name %></h3>
<h3><%= @review.rating %> stars</h3>
<h3>Comment:</h3>
  <p><%= @review.content_body %></p>

<p><%= link_to "Edit review", edit_product_review_path(@product, @review) %></p>
<p><%= link_to "Delete review", product_review_path(@product, @review),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to product", product_path(@product) %></p>